server:
  port: 8080

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
  devtools:
    restart:
      enabled: true #开启热部署
      additional-paths: src/main/java #监控的文件夹
      exclude: static/**,public/** #不监控的文件夹
  freemarker:
    cache: false #页面不加载缓存，修改页面后立即生效
    charset: UTF-8
  # session 失效时间
  session:
    timeout: 86400



# Mybatis-Plus Config
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
